In [1]:
import numpy as  np

In [5]:
arr1 = np.array([34,45,67,89])

In [8]:
arr1

array([34, 45, 67, 89])

In [10]:
arr2 = np.array([34,45,67,89])

In [12]:
arr2

array([34, 45, 67, 89])

In [20]:
np.__version__

'1.26.4'

In [22]:
arr3 = np.array({34,45,67,89})

In [24]:
arr3

array({89, 34, 67, 45}, dtype=object)

In [26]:
arr3.sum()

{34, 45, 67, 89}

In [28]:
arr3.dtype

dtype('O')

In [32]:
arr4 = np.array((34,45,67,89))

In [34]:
arr4

array([34, 45, 67, 89])

In [36]:
arr4.sum()

235

In [38]:
arr4.dtype

dtype('int64')

# Dimensions in numpy

In [40]:
a=np.array(45)

In [42]:
b=np.array((45,65))

In [44]:
c=np.array(((45,60),(78,90)))

In [46]:
d=np.array((((45,60),(78,90)),((40,40),(80,80))))

In [48]:
#Dimension = ndim
a.ndim

0

In [50]:
b.ndim

1

In [52]:
c.ndim

2

In [54]:
d.ndim

3

In [82]:
print(a)

45


In [84]:
print(b)

[45 65]


In [86]:
print(c)

[[45 60]
 [78 90]]


In [88]:
print(d)

[[[45 60]
  [78 90]]

 [[40 40]
  [80 80]]]


In [56]:
e=np.array((45,65),ndmin=5)

In [58]:
e

array([[[[[45, 65]]]]])

In [96]:
print(e)

[[[[[45 65]]]]]


# Array Indexing in Numpy

In [60]:
b[1]

65

In [62]:
c[1]

array([78, 90])

In [64]:
c[0][1]

60

In [66]:
d[0]

array([[45, 60],
       [78, 90]])

In [84]:
d[1]

array([[40, 40],
       [80, 80]])

In [82]:
d[1][1]

array([80, 80])

In [80]:
d[1][1][1]

80

In [94]:
z=np.array(([43,56,81,90,102,40],[41,54,80,99,98,97]))

In [96]:
z[0][1]

56

In [98]:
z[1,3]

99

In [100]:
z[1,-4]

80

In [102]:
z[0,1:3]

array([56, 81])

In [104]:
y=np.array([41,54,80,99,98,97])

In [106]:
y[0]

41

In [108]:
y[5]

97

In [110]:
y[1:5]

array([54, 80, 99, 98])

In [112]:
y[1:6:2]

array([54, 99, 97])

# Data Type Numpy

In [116]:
y.dtype

dtype('int64')

In [118]:
x=np.array([41.5,54.6,80,99,98.5,97])

In [122]:
x.dtype

dtype('float64')

In [124]:
u=np.array([1+2j,5+3j,6+4j])

In [126]:
u

array([1.+2.j, 5.+3.j, 6.+4.j])

In [130]:
u.dtype

dtype('complex128')

In [132]:
m=np.array([1+2j,5+3j,6+4j], dtype='complex')

In [134]:
m

array([1.+2.j, 5.+3.j, 6.+4.j])

In [138]:
n=np.array([41.5,54.6,80,99,98.5,97], dtype='S')

In [140]:
n

array([b'41.5', b'54.6', b'80', b'99', b'98.5', b'97'], dtype='|S4')

In [144]:
print(n)

[b'41.5' b'54.6' b'80' b'99' b'98.5' b'97']


In [152]:
n.dtype

dtype('S4')

In [154]:
n.sum

<function ndarray.sum>

In [158]:
ab=np.array(['abc','apple','ball'])

In [160]:
ab.dtype

dtype('<U5')

In [162]:
ab

array(['abc', 'apple', 'ball'], dtype='<U5')

In [164]:
print(ab)

['abc' 'apple' 'ball']


# COPY

In [167]:
#When value is copied, value is changed only on one variable
te = x.copy()

In [169]:
te

array([41.5, 54.6, 80. , 99. , 98.5, 97. ])

In [171]:
te[4]

98.5

In [173]:
te[4]=56

In [175]:
te[4]

56.0

In [177]:
te

array([41.5, 54.6, 80. , 99. , 56. , 97. ])

In [179]:
x

array([41.5, 54.6, 80. , 99. , 98.5, 97. ])

In [193]:
#When value is assigned in view, it is changed in both variable
cd=x.view()

In [183]:
cd

array([41.5, 54.6, 80. , 99. , 98.5, 97. ])

In [185]:
x

array([41.5, 54.6, 80. , 99. , 98.5, 97. ])

In [187]:
cd[0]=20

In [189]:
cd

array([20. , 54.6, 80. , 99. , 98.5, 97. ])

In [191]:
x

array([20. , 54.6, 80. , 99. , 98.5, 97. ])

# Shape

In [196]:
x.shape

(6,)

In [200]:
z=np.array(([43,56,81,90,102,40],[41,54,80,99,98,97]))

In [218]:
z

array([[ 43,  56,  81,  90, 102,  40],
       [ 41,  54,  80,  99,  98,  97]])

In [202]:
z.shape

(2, 6)

In [204]:
print(z)

[[ 43  56  81  90 102  40]
 [ 41  54  80  99  98  97]]


In [206]:
xyz=np.array((((45,60),(78,90)),((40,40),(80,80))))

In [210]:
xyz.ndim

3

In [212]:
xyz.shape

(2, 2, 2)

In [227]:
z=z.reshape(4,3)
z
#z.reshape (4,5) will not work as 4*3=12 but 4*5 =20 which is not equal.. So, cannot reshape

array([[ 43,  56,  81],
       [ 90, 102,  40],
       [ 41,  54,  80],
       [ 99,  98,  97]])

# Array Iteration

In [229]:
for x in z:
    print(x)

[43 56 81]
[ 90 102  40]
[41 54 80]
[99 98 97]


In [ ]:
for i in range()

In [239]:
for x in z:
    l=len(x)
    for i in range(l):
        for j in range(0,l-1):
            print(z[i][j])

43
56
90
102
41
54
43
56
90
102
41
54
43
56
90
102
41
54
43
56
90
102
41
54


In [241]:
for a in x:
    print(a)

99
98
97


# Array Join

In [244]:
ad = np.array([45,55,56,89])

In [248]:
dc = np.array([54,78,90,99])

In [250]:
ad + dc

array([ 99, 133, 146, 188])

In [252]:
np.concatenate((ad,dc))

array([45, 55, 56, 89, 54, 78, 90, 99])

In [260]:
#alternate of concatenate
np.hstack((ad,dc))

array([45, 55, 56, 89, 54, 78, 90, 99])

In [254]:
np.vstack((ad,dc))

array([[45, 55, 56, 89],
       [54, 78, 90, 99]])

In [258]:
np.dstack((ad,dc))

array([[[45, 54],
        [55, 78],
        [56, 90],
        [89, 99]]])

# Split

In [265]:
np.array_split(ad,4)

[array([45]), array([55]), array([56]), array([89])]

In [267]:
np.array_split(ad,3)

[array([45, 55]), array([56]), array([89])]

In [269]:
np.array_split(ad,2)

[array([45, 55]), array([56, 89])]

In [271]:
np.array_split(ad,5)

[array([45]), array([55]), array([56]), array([89]), array([], dtype=int64)]

In [273]:
np.array_split(ad,6)

[array([45]),
 array([55]),
 array([56]),
 array([89]),
 array([], dtype=int64),
 array([], dtype=int64)]

In [275]:
np.array_split(ad,7)

[array([45]),
 array([55]),
 array([56]),
 array([89]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

In [285]:
ac = np.array(([45,56],[70,99],[65,55],[43,45],[23,22],[54,56]))

In [293]:
ac

array([[45, 56],
       [70, 99],
       [65, 55],
       [43, 45],
       [23, 22],
       [54, 56]])

In [289]:
np.hsplit(ac,2)

[array([[45],
        [70],
        [65],
        [43],
        [23],
        [54]]),
 array([[56],
        [99],
        [55],
        [45],
        [22],
        [56]])]

In [291]:
np.vsplit(ac,2)

[array([[45, 56],
        [70, 99],
        [65, 55]]),
 array([[43, 45],
        [23, 22],
        [54, 56]])]

# Numpy Search

In [313]:
ac

array([[45, 56],
       [70, 99],
       [65, 55],
       [43, 45],
       [23, 22],
       [54, 56]])

In [296]:
np.where(ac==56)

(array([0, 5]), array([1, 1]))

In [298]:
q = np.array([45,55,66,89,54,78,90,99])

In [300]:
np.where(q==89)

(array([3]),)

# SORT

In [305]:
np.sort(q)

array([45, 54, 55, 66, 78, 89, 90, 99])

In [307]:
q

array([45, 55, 66, 89, 54, 78, 90, 99])

In [309]:
q*3

array([135, 165, 198, 267, 162, 234, 270, 297])

In [311]:
q/5

array([ 9. , 11. , 13.2, 17.8, 10.8, 15.6, 18. , 19.8])