In [10]:
import numpy as  np

In [14]:
arr1 = numpy.array([34,45,67,89])

In [16]:
arr1

array([34, 45, 67, 89])

In [20]:
arr2 = np.array([34,45,67,89])

In [22]:
arr2

array([34, 45, 67, 89])

In [24]:
np.__version__

'1.26.4'

In [34]:
arr3 = numpy.array({34,45,67,89})

In [36]:
arr3

array({89, 34, 67, 45}, dtype=object)

In [44]:
arr3.sum()

{34, 45, 67, 89}

In [48]:
arr3.dtype

dtype('O')

In [38]:
arr4 = numpy.array((34,45,67,89))

In [40]:
arr4

array([34, 45, 67, 89])

In [42]:
arr4.sum()

235

In [46]:
arr4.dtype

dtype('int64')

# Dimensions in numpy

In [52]:
a=np.array(45)

In [54]:
b=np.array((45,65))

In [56]:
c=np.array(((45,60),(78,90)))

In [60]:
d=np.array((((45,60),(78,90)),((40,40),(80,80))))

In [78]:
#Dimension = ndim
a.ndim

0

In [72]:
b.ndim

1

In [74]:
c.ndim

2

In [76]:
d.ndim

3

In [82]:
print(a)

45


In [84]:
print(b)

[45 65]


In [86]:
print(c)

[[45 60]
 [78 90]]


In [88]:
print(d)

[[[45 60]
  [78 90]]

 [[40 40]
  [80 80]]]


In [92]:
e=np.array((45,65),ndmin=5)

In [94]:
e

array([[[[[45, 65]]]]])

In [96]:
print(e)

[[[[[45 65]]]]]
